version: "3"

services:
  ssr:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
    # enviroment:
    #   - ABC:123
    # volumes:
    #   - .:/usr/src/app
    # depends_on:
    #   - db
